name: py2rigs
channels:
  - defaults
dependencies:
  - pip
  - python=3.9
  - pip:
      - h5py==3.10.0
      - json5==0.9.6
      - jsonschema==4.21.1
      - matplotlib==3.7.4
      - natsort==8.4.0
      - numpy==1.24.4
      - pyyaml==6.0.1
      - umap-learn==0.5.4
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - tifffile==2023.7.10
      - tk==0.1.0
      - tkfilebrowser==2.3.2
      - tqdm==4.66.1
      - pyyaml==0.2.5
